name: Simple CI Pipeline
on: [push]
jobs:
  SimpleCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out repository code & install node
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
          cache: 'yarn'
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test