name: ReactTimerBar CI/CD Pipeline
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out repository code & install node
        uses: actions/setup-node@v2
        with: 
          node-version: '16'